# api/config.py
EMAIL_COLUMN = 'email_addr'
# SHEETS_TO_CHECK = ["PREMIUM", "GSUITE", "GMAIL", "OFFICE", "OUTLOOK", "HOTMAIL", "YAHOO", "AOL", "COMCAST", "MAIL", "EARTHLINK", "COX"]
SHEETS_TO_CHECK = ["GMAIL", "AOL", "OUTLOOK", "HOTMAIL"]
VERIFIED_SHEET_NAME = 'VERIFIED'